export const projects = [
  {
    name: "Holidaze - Accommodation booking site",
    content: "This was my final exam, tasked in creating a booking website for accommodations in Bergen, Norway. This project includes a searchbar typeahead, fetching items from wordpress REST api, login possibility and contacting possibilites. This project is ment to represent my entire learing curve as a student at Noroff through the years.",
    image: "../../img/1.JPG",
    modalNr: "modal-five",
    websiteLink: "https://holidazeeivindsimonsen.netlify.app/",
    githubLink: "https://github.com/Noroff-FEU-Assignments/project-exam-2-eivindsimonsen",
  },
  {
    name: "React knowledge test - JS-frameworks course assignment",
    content: "This was my JS-frameworks course assigment tast my second year as a frontend-developer. I was tasked in making a get request in react with axios, displaying received items both together and as seperate details pages. Also contains form validation and login possibilities.",
    image: "../../img/2.JPG",
    modalNr: "modal-four",
    websiteLink: "https://github.com/Noroff-FEU-Assignments/js-frameworks-course-assignment-eivindsimonsen",
    githubLink: "https://github.com/Noroff-FEU-Assignments/js-frameworks-course-assignment-eivindsimonsen",
  },
  {
    name: "Running Man - E-commerce for shoes",
    content: "This was my semester project the second year of school, and we were tasked in creating an e-commerce for shoes. The website is taking use of STRAPI.IO, which I use to upload images, and making it possible to log in and out. I also take use of POST/GET/PUT and DELETE requests for an eventual user to create and add products by themselves.",
    image: "../../img/Capture7.JPG",
    modalNr: "modal-three",
    websiteLink: "https://running-man.netlify.app/index.html",
    githubLink: "https://github.com/EivindSimonsen/semester-project-2",
  },
  {
    name: "Discord website clone",
    content: "This project was for practicing my react skills with use of components and stylings. My goal was to design the home page of the discord website without getting help from inspecting their code.",
    image: "../../img/Capture8.JPG",
    modalNr: "modal-two",
    websiteLink: "https://github.com/eivindsimonsen/discord-clone",
    githubLink: "https://github.com/eivindsimonsen/discord-clone",
  },
  {
    name: "Guitar Kings - E-commerce website of guitars",
    content: "This project was my first complete website. It only takes use of HTML and CSS, and was only meant for taking those languages into practice.",
    image: "../../img/Capture2.JPG",
    modalNr: "modal-one",
    websiteLink: "https://silly-golick-a22c03.netlify.app/",
    githubLink: "https://github.com/EivindSimonsen/guitarkings",
  },
];
