export const projects = [
  {
    name: "Personalforeningen i Coop Øst",
    content: "My boss reached out and said he needed a website for Coop Øst's own staff association. Me and a fellow developer set out for the challenge. The websites purpose is to give information about what the association can offer for employees in Coop Øst. The association offers among other things, cheaper cabin rental. The website is built with REACT and SASS as pre-processor, with wordpress REST api for content. My boss can now fully change the content on the page, without reaching out to the devs.",
    image: "../../img/personalforeningen.JPG",
    modalNr: "modal-six",
    websiteLink: "https://personalforeningen.netlify.app/",
    githubLink: "https://github.com/emiost/personal",
  },
  {
    name: "Holidaze - Accommodation booking site",
    content: "This was my final exam, tasked in creating a booking website for accommodations in Bergen, Norway. This project includes a searchbar typeahead, fetching items from wordpress REST api, login possibility and contacting possibilites. This project is ment to represent my entire learing curve as a student at Noroff through the years.",
    image: "../../img/holidaze.JPG",
    modalNr: "modal-five",
    websiteLink: "https://holidazeeivindsimonsen.netlify.app/",
    githubLink: "https://github.com/Noroff-FEU-Assignments/project-exam-2-eivindsimonsen",
  },
  {
    name: "Running Man - E-commerce for shoes",
    content: "This was my semester project the second year of school, and we were tasked in creating an e-commerce for shoes. The website is taking use of STRAPI.IO, which I use to upload images, and making it possible to log in and out. I also take use of POST/GET/PUT and DELETE requests for an eventual user to create and add products by themselves.",
    image: "../../img/runningman.JPG",
    modalNr: "modal-three",
    websiteLink: "https://running-man.netlify.app/index.html",
    githubLink: "https://github.com/EivindSimonsen/semester-project-2",
  },
  {
    name: "Discord website clone",
    content: "This project was for practicing my react skills with use of components and stylings. My goal was to design the home page of the discord website without getting help from inspecting their code.",
    image: "../../img/discord.JPG",
    modalNr: "modal-two",
    websiteLink: "https://github.com/eivindsimonsen/discord-clone",
    githubLink: "https://github.com/eivindsimonsen/discord-clone",
  },
  {
    name: "Guitar Kings - E-commerce website of guitars",
    content: "This project was my first complete website. It only takes use of HTML and CSS, and was only meant for taking those languages into practice.",
    image: "../../img/guitarkings.JPG",
    modalNr: "modal-one",
    websiteLink: "https://silly-golick-a22c03.netlify.app/",
    githubLink: "https://github.com/EivindSimonsen/guitarkings",
  },
];
