export const projects = [
  {
    name: "Discord website clone",
    content: "This project was for practicing my react skills with use of components and stylings. My goal was to design the home page of the discord website without getting help from inspecting their code.",
    image: "../../img/Capture8.JPG",
    modalNr: "modal-five",
    websiteLink: "https://github.com/eivindsimonsen/discord-clone",
    githubLink: "https://github.com/eivindsimonsen/discord-clone",
  },
  {
    name: "Running Man - E-commerce for shoes",
    content: "This was my semester project the second year of school, and we were tasked in creating an e-commerce for shoes. The website is taking use of STRAPI.IO, which I use to upload images, and making it possible to log in and out. I also take use of POST/GET/PUT and DELETE requests for an eventual user to create and add products by themselves.",
    image: "../../img/Capture7.JPG",
    modalNr: "modal-six",
    websiteLink: "https://running-man.netlify.app/index.html",
    githubLink: "https://github.com/EivindSimonsen/semester-project-2",
  },
  {
    name: "Sims & Kryl - Blog website",
    content: "This website was a school project were we was tasked to create a blog post website. This website uses wordpress rest API to retrieve posts created in wordpress.",
    image: "../../img/Capture.JPG",
    modalNr: "modal-one",
    websiteLink: "https://simsandkrylportfolio.netlify.app/",
    githubLink: "https://github.com/EivindSimonsen/project-exam-1",
  },
  {
    name: "Guitar Kings - E-commerce website of guitars",
    content: "This project was my first complete website. It only takes use of HTML and CSS, and was only meant for taking those languages into practice.",
    image: "../../img/Capture2.JPG",
    modalNr: "modal-two",
    websiteLink: "https://silly-golick-a22c03.netlify.app/",
    githubLink: "https://github.com/EivindSimonsen/guitarkings",
  },
  {
    name: "Vermint Gallery - E-commerce for paintings",
    content: "This is a project I did for my brother. He paints and want to sell. It takes use of HTML, CSS and javascript. For this project i created a wordpress rest API, so that my brother could add his products in wordpress without having to change the source code.",
    image: "../../img/Capture3.JPG",
    modalNr: "modal-three",
    websiteLink: "https://vermintgallery.netlify.app/",
    githubLink: "https://github.com/EivindSimonsen/vermint-gallery",
  },
  {
    name: "Community Science Museum - Semester project",
    content: "For the semester project, i was tasked in creating a website for a fictional musem. I was to represent a website for all ages, and create interest for potential visitors.",
    image: "../../img/Capture4.JPG",
    modalNr: "modal-four",
    websiteLink: "https://escommunitysciencemuseum.netlify.app/",
    githubLink: "https://github.com/EivindSimonsen/semester-project",
  },
];
